[variables]
DATABASE_URL = "postgresql://dummy:dummy@localhost:5432/dummy"
PRISMA_SKIP_POSTINSTALL_GENERATE = "1"

[phases.setup]
nixPkgs = ["nodejs"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"
